#  Linear Algebra Fundamentals for Data Science

Source code from Medium's article ["Linear Algebra Fundamentals for Data Science"](https://bit.ly/33o7iEV), written by [Fortune Uwha](https://fortune-uwha.medium.com/).

# Import libaries

In [1]:
import numpy as np

# Scalars, Vectors, Matrices and Tensors

In [2]:
# Declare a scalar as int
#
s = 3
print(s)

3


In [3]:
# Or as an array
#
s_array = np.array(3)
print(s_array)

3


In [4]:
# Create a vector
#
v = np.array([3, -5, 6, 1])
print(v)

[ 3 -5  6  1]


In [5]:
# Create a matrix
#
m = np.array([[2, 3, 1], [5, 6, 3]])
print(m)

[[2 3 1]
 [5 6 3]]


In [6]:
# Or
#
M = np.arange(6).reshape(2, 3)
print(M)

[[0 1 2]
 [3 4 5]]


In [7]:
# Create a Tensor
#
m1 = np.array([[2, 3, 1], [5, 6, 3]])

m2 = np.array([[3, -1, 5], [9, 2, 4]])

# Tensor: m1 + m2
#
t = np.array([m1, m2])

print(t)
print(t.shape)

[[[ 2  3  1]
  [ 5  6  3]]

 [[ 3 -1  5]
  [ 9  2  4]]]
(2, 2, 3)


In [9]:
T = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
              [[11, 12, 13], [14, 15, 16], [17, 18, 19]]])

print(T)
print(T.shape)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]]
(2, 3, 3)
